# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modifiel_time',
            new_name='modified_time',
        ),
    ]
