# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20171010_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='number_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
