# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_number_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='number_view',
        ),
        migrations.AddField(
            model_name='post',
            name='Num_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
